{% set name = "rst2html5" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rst2html5-{{ version }}.tar.gz
  sha256: 309998c85fab028f2fcb01a2ccdc886db0afc4398262e795a02ea9c4d0f32ae9

build:
  number: 0
  noarch: python
  entry_points:
    - rst2html5 = rst2html5_:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - docutils >=0.13.1
    - genshi >=0.7
    - pygments >=2.5
    - python >=3.6

test:
  imports:
    - rst2html5
  commands:
    - pip check
    - rst2html5 --help
  requires:
    - pip

about:
  home: https://foss.heptapod.net/doc-utils/rst2html5
  summary: Generates (X)HTML5 documents from standalone reStructuredText sources
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
